[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.30"

[[constraint]]
  name = "github.com/apex/log"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
