// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

package root

var (
	// Version of the program.
	Version = "9999.999.99999"
	// Commit of the program
	Commit = "development"
	// BuildTime of the program
	BuildTime = "Right Now"
)
